
version: '3.3'
services:

  # Log collector, buffer, filter and shipper
  fluentd:
    image: dockertutorial/fluentd-elasticsearch
    networks:
      - logging
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    logging:
      driver: json-file
    deploy:
      mode: global
      restart_policy:
        condition: on-failure

  # Log index and search
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.2
    environment:
      ES_JAVA_OPTS: '-Xms256m -Xmx256m'
      xpack.security.enabled: 'false'
      xpack.monitoring.enabled: 'false'
      xpack.graph.enabled: 'false'
      xpack.watcher.enabled: 'false'
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - logging
    logging:
      driver: json-file
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          memory: 1g

  # Log search UI via elasticsearch
  kibana:
    image: docker.elastic.co/kibana/kibana:5.5.2
    networks:
      - logging
      - traefik
    logging:
      driver: json-file
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.port=5601"
        - "traefik.docker.network=traefik"
        - "traefik.frontend.rule=Host:kibana.${DOMAIN_NAME}"

networks:
  # Log aggregation network
  logging:
    external: true
  # Traefik reverse proxy network
  traefik:
    external: true

volumes:
  esdata:
